name: Build and Test the site without deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push events for the main branch
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
      # Checkout git branch
      - name: Checkout
        uses: actions/checkout@v3
      # Cache gems
      - name: Cache Gems
        id: cache-ruby
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      # If cache wasn't hit and restored, install dependencies
      - name: Install Ruby dependencies
        if: steps.cache-ruby.outputs.cache-hit != 'true'
        run: gem install bundler && bundle install

      # Build the site to produce output
      - name: Build jekyll site
        run: bundle exec jekyll build

      # Run static test scripts
      #- name: Run Test Scripts
      #  run: bash _site/run_tests.sh
      - name: List directory structure of build target directory
        run: tree _site
