name: Build and Test the site without deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push events for the main branch
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
      # Checkout git branch
      - name: Checkout
        uses: actions/checkout@v3
      # Cache gems
      - name: Cache Gems
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      # Build the site and push new state to branch gh-pages
      - name: Build Jekyll Site
        uses: helaili/jekyll-action@2.3.1    # Choose any one of the Jekyll Actions
        with:                                # Some relative inputs of your action
          keep_history: true
          token: ${{ secrets.GITHUB_TOKEN }}
          build_only: true

      - name: Run Test Scripts
        run: | 
          for f in *.sh; do \
            bash "$f" \
          done
        working-directory: tests