name: Build and Test the site without deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on pull requests for the main branch
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
      # Checkout git branch
      - name: Checkout
        uses: actions/checkout@v3

      # Automatic setup of Ruby environment and dependencies
      - name: Perform Ruby Setup
        uses: ruby/setup-ruby
        with:
          ruby-version: 2.7
          bundler-cache: true

      # Build the site to produce output
      - name: Build jekyll site
        run: bundle exec jekyll build

      # Run static test scripts
      #- name: Run Test Scripts
      #  run: bash _site/run_tests.sh
      - name: List directory structure of build target directory
        run: tree _site
