name: Build and run Cypress tests

# Controls when the workflow will run
on:
  # Allows the workflow to be called from another workflow
  workflow_call:
    inputs:
      browser:
        description: 'Browser to run the tests on'
        type: string
        required: true
        default: electron
      viewport-width:
        description: 'Width of the viewport to test'
        type: string
        required: true
        default: 1000
      viewport-height:
        description: 'Width of the viewport to test'
        type: string
        required: true
        default: 660
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      browser:
        description: 'Browser to run the tests on'
        type: choice
        options:
          - electron
          - chrome
          - firefox
          # Optional: add beta builds
        required: true
        default: electron
      viewport-width:
        description: 'Width of the viewport to test'
        type: string
        required: true
        default: '1000'
      viewport-height:
        description: 'Width of the viewport to test'
        type: string
        required: true
        default: '660'

jobs:
  cypress-tests:
    name: Cypress Tests
    runs-on: ubuntu-latest
    steps:
      # Checkout git branch
      - name: Checkout
        uses: actions/checkout@v3

      # Automatic setup of Ruby environment and dependencies
      - name: Perform Ruby Setup
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      # Automatic installation of node, modules, building and serving site
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v2
        with:
          start: bundle exec jekyll serve --no-watch # No changes should happen -> no need to watch
          wait-on: 'http://localhost:4000' # Ensure server comes up before tests start, in case build takes longer
          browser: ${{ github.event.input.browser }}
          # Environment variables for matrix testing, such as viewport size etc.
          env: CYPRESS_VIEWPORT_WIDTH=${{ github.event.input.viewport-width }},CYPRESS_VIEWPORT_HEIGHT=${{ github.event.input.viewport-width }}