#Mark issues from Task templates invalid if they're created by members from outside the team
name: Validate Issues
on:
  issues:
    types:
      - labeled

env:
  internal_labels: '["content", "design", "technical"]'
  move_labels: '["bug", "accessibility", "content", "design", "technical"]'
  close_labels: '["duplicate", "invalid"]'
  issue_number: ${{ github.event.number }}
      
jobs:
  check-labels:
    name: Check Issue Label
    runs-on: ubuntu-latest
    permissions:
      issues: write
    if: contains(fromJSON(${{env.internal_labels}}), github.event.label.name) 
    steps:
      - name: Check if organization member
        id: validate
        uses: jamessingleton/is-organization-member@1.0.1
        with:
          organization: skolio
          username: ${{ github.event.issue.user.login }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Label invalid issues
        if: steps.validate.outputs.result == 'false'
        uses: andymckay/labeler@1.0.4
        with:
          add-labels: "invalid"
          remove-labels: ${{ github.event.label.name }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Comment on invalid issues
        if: steps.validate.outputs.result == 'false'
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ env.issue_number }}
          body: |
              This issue has been marked as invalid and will be closed. 
              [Team] Issue Templates and the labels content, design and technical are intended for internal use by organization members only.
              Please use Templates marked with [Public] and refrain from adding any additional labels on your own. 
    outputs:
      valid: ${{ steps.validate.outputs.result }}
      
  move-issues:
    name: Move or Close Issues by label
    runs-on: ubuntu-latest
    needs: check-labels
    if: needs.check-labels.outputs.valid == 'true'
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      issues: write
    steps: 
      - name: Close invalid issues
        if: contains(fromJSON(${{env.close_labels}}), github.event.label.name)
        uses: peter-evans/close-issue@v2
        with:
          comment: Automatically closing this issue as ${{ github.event.label.name }}
      
      - name: Move valid issues to Project board
        if: contains(fromJSON(${{env.move_labels}}), github.event.label.name)
        uses: srggrs/assign-one-project-github-action@1.2.1
        with:
          project: 'https://github.com/skolio/skolio.github.io/projects/3'
          column_name: 'To do'
